id: 56
name: fbEmailGetJSON
category: f_formblocks
properties: 'a:0:{}'

-----

/**
 * fbEmailGetJSON
 *
 * A snippet for FormBlocks that grabs the raw JSON data from the Properties column of the site_content table.
 * This data is being generated by ContentBlocks, and is used on the website to display the actual form.
 *
 * The result is being fed to the SIMPLX Widgeteer snippet.
 * This snippet is used to automatically generate the email template, based on the CB JSON data. It will template the JSON into rows for each field.
 * By using the complete output (and not f.i. cbGetFieldContent), the order of the fields is always correct in the email.
 *
 * @author Hugo Peek
 */

$resourceID = $modx->getOption('formID', $scriptProperties, '');
$resource = $modx->getObject('modResource', $resourceID);

$rawData = $resource->getProperty('linear', 'contentblocks');
$json = $modx->toJSON($rawData);

return $json;

//$sql = 'SELECT `properties` FROM `'.$modx->getOption(xPDO::OPT_TABLE_PREFIX).'site_content` WHERE `id` = '.$resourceID.'';
//$result = $modx->query($sql);

//$rawData = $result->fetch(PDO::FETCH_ASSOC);

//return implode('', $rawData);